### ISSUE TITLE
CRISPRme output

### ISSUE THREAD

**Issue by misik** [pinellolab/CRISPRme#1]
Hi,

I ran CRISPRme for a guide sequence and included 1000 Genome vcf files to find out how variants effect the OT sites. I found some sites that didn't have any variants mapping but were reported as having lower number of mismatches/bulges in "MMBLG_Mismatches | MMBLG_Bulge_Size | MMBLG_Total" columns compared to "Mismatches | Bulge_Size | Total" columns.
The OT sequence is same in "DNA" and "MMBLG_DNA" columns but the alignment to guide is different.
aggCACTAG-aTTGACaCACAGG vs aggCACTAGA-TTGACaCACAGG
All variation related rows have "n" value for this example, so there is no variant mapping to this genomic region.
Is this a bug or should I interpret the results in a different way?

Thank you,
Meltem

**Comment by lindayqlin** [comment]
Hi Meltem,

Thanks for trying out CRISPRme and for your question! Sorry for the delayed reply on our end.

I believe this is a feature, not a bug. As you point out, the actual OT sequence reported is identical in both scenarios, but they are alternative alignments relative to each other. The main output of CRISPRme is our "integrated_results" file, which I would encourage you to take a look at if possible. It reports a single candidate off-target site per genomic region by highest CFD score (cutting frequency determination score, an empirically derived metric of predicted cleavage potential from Doench et al. Nat Biotechnol 2016) as well as fewest mismatches + bulges, merging all possible off-target sequences and alternative alignments thereof (as in your example) within a 3 bp window by default. I would suggest that you refer to that as the main CRISPRme results file.

Please let us know if you have any further questions!

Thanks,
Linda
