### ISSUE TITLE
CrisprMe website missing gene annotation information

### ISSUE THREAD

**Issue by joki-MG** [pinellolab/CRISPRme#23]
Tried using the webtool to test the example guide targeting BCL11A in the paper, Human genetic diversity alters off-target outcomes of therapeutic gene editing (https://doi.org/10.1038/s41588-022-01257-y)

CRISPRme does identify the CPS1 off-target site as demonstrated in the paper at location chr2:210530658 but it is not annotated with the CPS1 gene or rsID. 

<img width="1009" alt="webtool_output_1" src="https://user-images.githubusercontent.com/91500643/219791571-5820ad37-81c2-41bd-9dfb-05afb6a6ccca.png">

<img width="1133" alt="webtool_output_2" src="https://user-images.githubusercontent.com/91500643/219791587-2c12c4c0-a61c-475b-8f34-133c1b889e1d.png">

**Comment by ManuelTgn** [comment]
Hello,
thanks for highlighting the issue. We fixed the bug on CRISPRme's website, and now it works as expected. 
The command line version of the tool works as expected as well.
