### ISSUE TITLE
Impact of variations for On target

### ISSUE THREAD

**Issue by Davood-Norouzi** [pinellolab/CRISPRme#24]
Hi Crisprme team,

Thanks for the amazing tool! I am using the latest version 2.10.0 on conda. I am testing Crisprme for now, but will most likely get an industry license very soon. Please let me know how that works.

I have few questions/requests for now.

1. In which files/tables can I find information about the off-targets' closest gene(s), whether the off target is coding region or intronic region or a regulatory element? What about the type of gene information, whether it is a tumor suppressor or there is a PAM creation? Where are these information stored? Right now, I am only using the 1000G variants.

2. Are the reported CFD scores homology based only? Or the score are more sophisticated and depend on where the mismatch has occurred?

3. Lastly and more importantly, I would like to see the impact of genetic variation on the on-target specificity. Will genetic variation reduce the chance of being on target. Are there sub-populations in which the on-target PAM is disabled? These are the type of information I would like to see in the output. Hope this is rather easy to implement.

Looking forward to hearing from you,
-Davood

**Comment by samuelecancellieri** [comment]
Hi @Davood-Norouzi,

answering your questions,
1. in the file *.integrated_results.tsv you will find columns named PAM_creation and Annotation_closest_gene_name, Annotation_closest_gene_ID, Annotation_closest_gene_distance_(kb), these columns contain information about genes and eventually PAM creation.
2. CFD score is based on homology and position of the mismatch/bulge, as stated in [10.1038/nbt.3437](https://doi.org/10.1038%2Fnbt.3437)
3. these informations are produced after the complete-search, if you open the results on the website, you can see the graphs and images about populations. There are no others analysis done on populations, just reported data.

Thanks for the question and the software usage.

Best,
