### ISSUE TITLE
Y Chromosome 1000G Project

### ISSUE THREAD

**Issue by wmack24** [pinellolab/CRISPRme#25]
Hi CRISPRme Team,
Quick question: I noticed the installation scripts do not download the 1000G Project VCF for the Y chromosome.
Is this expected behavior? Thank you so much!

**Comment by ManuelTgn** [comment]
Hi,

variants data for chrY is not available on the 1000 Genomes Project data portal, as you can see on their website at https://www.internationalgenome.org/data-portal/data-collection/grch38.
Additionally, searching for off-targets on chrX is usually sufficient for most applications, and the results obtained are often similar.

**Comment by ManuelTgn** [comment]
Hi @wmack24,

as mentioned in our previous reply, unfortunately there are no data available for chrY on 1000 Genomes data portal. As soon as chrY data will be available, we will integrate them in CRISPRme. 
However, currently CRISPRme reports potential off-targets found on chrY reference sequence.

Thank you for pointing out this important issue,
Manuel
