### ISSUE TITLE
single chromosome run

### ISSUE THREAD

**Issue by dsantesmasses** [pinellolab/CRISPRme#28]
Hi,

Is it possible to run CRISPRme on a single chromosome? Ideally keeping all chromosomes in the same `Genomes/` folder.

Thanks!

**Comment by ManuelTgn** [comment]
Hi @dsantesmasses,

Absolutely! CRISPRme can definitely be run on a single chromosome. However, please keep in mind that for the current design of CRISPRme, the chromosome FASTA should be placed in its own folder. You can potentially create a new directory within the `Genomes/` directory which contains your chromosome of interest. For example, if you are interested in analyzing chromosome 22, you could follow these steps:
```
cd Genomes # access Genomes/
mkdir chr22_folder # create a folder for only chr22
cp chr22.fa chr22_folder # copy chr22 in chr22_folder keeping the original FASTA
# run crisprme on only chr22
cd ..
crisprme.py complete-search  --genome Genomes/chr22_folder # other args
```

I hope this helps! If you have any further questions or concerns, please don't hesitate to let us know.

Best,
Manuel

**Comment by dsantesmasses** [comment]
Thanks for the quick reply!
Should I do the same for the VCF files? Does the program load all VCFs in the folder or will it look for the corresponding one based on file name?

Thanks!

**Comment by dsantesmasses** [comment]
Hi,

it seems the `VCFs` folder should contain only the same chromosome as `Genomes` folder, otherwise it throws an error because the chromosome fasta is not found.

Would you recommend to split a whole genome run into individual chromosomes? Do you anticipate any potential problem?

Thanks!

**Comment by dsantesmasses** [comment]
Hi!

I am running CRISPRme v2.1.0 on individual chromosomes so I can run each chromosome in parallel. I am not using VCFs files. This is what my command line looks like.

```
        """crisprme.py complete-search \
            --genome Genomes/{wildcards.chrom}/ \
            --guide {input} \
            --pam PAMs/20bp-NGG-SpCas9.txt \
            --annotation Annotations/encode+gencode.hg38.bed \
            --gene_annotation Annotations/gencode.protein_coding.bed \
            --mm 6 \
            --bDNA 1 \
            --bRNA 1 \
            --merge 3 \
            --output '20230327/{wildcards.chrom}/{wildcards.id}/{wildcards.name}/' \
            --thread {threads}
        """
```

It seem all output files are generated, but for some chromosomes the `log_error_no_check.txt` file contains an error related to `./radar_chart_dict_generator.py`. The error is the following

```
Traceback (most recent call last):
  File "./radar_chart_dict_generator.py", line 38, in <module>
    inSamplesIDFile = open(sys.argv[3], 'r').readlines()  # sampleID file
FileNotFoundError: [Errno 2] No such file or directory: 'dummy.txt'
rm: cannot remove 'dummy.txt': No such file or directory
``` 

I have 2 questions, 1) should I be concerned about incomplete output if the error log is not clean? and 2) why the error is not consistently in all chromosomes log file?

Thanks very much!

**Comment by samuelecancellieri** [comment]
Hi @dsantesmasses,
thanks a lot for using the software.

The problem you encountered was probably caused by the concurrency using too many separate searches with single chromosomes, following the suggestion of @ManuelTgn you can run the software using a directory with all the chromosome FASTAs.

I hope this help you,
thanks again.

Best,

**Comment by dsantesmasses** [comment]
Hi @samuelecancellieri ,

Thanks very much your reply and for looking into this.

Sorry my message was not clear, but as you can see in the command line example above I followed @ManuelTgn suggestion and created a subfolder for each chromosome, eg `Genomes/chr1/chr1.fa`. By running CRISPRme on individual chromosomes the runtime is much shorter so I hope this is a good option.

In some cases I get the following error. Is this error downstream of the creation of the output file`integrated_results.tsv`? Can I assume the file is complete?

```
Traceback (most recent call last):
  File "./radar_chart_dict_generator.py", line 38, in <module>
    inSamplesIDFile = open(sys.argv[3], 'r').readlines()  # sampleID file
FileNotFoundError: [Errno 2] No such file or directory: 'dummy.txt'
rm: cannot remove 'dummy.txt': No such file or directory
```

Thanks!

**Comment by samuelecancellieri** [comment]
hi @dsantesmasses 
yeah the integrated result file is external to the creation of the radar charts,
the dummy file is just a replace file for when some optional file is not provided.
since the software is not expected to work with different chromosomes concurrently, the file can be removed and recreated multiple times generating the error, but the results will be fine.

thanks again for the interest and using the software.
best,
