### ISSUE TITLE
Is the dropbox test data not accessible anymore?

### ISSUE THREAD

**Issue by sdmiller93** [pinellolab/CRISPRme#33]
**Describe the bug**
Trying to download test data to test my installation: 

```
$ wget https://www.dropbox.com/s/urciozkana5md0z/crisprme_test.tar.gz?dl=1 -O crisprme_test.tar.gz
--2023-04-04 15:06:23--  https://www.dropbox.com/s/urciozkana5md0z/crisprme_test.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.18
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/urciozkana5md0z/crisprme_test.tar.gz [following]
--2023-04-04 15:06:23--  https://www.dropbox.com/s/dl/urciozkana5md0z/crisprme_test.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com/cd/0/get/B5gpbbCTnzZCiZiieBea8pMWQGbJ23D63L7ejpA053ciEAlNmWDQHGedfiSn7kZEdplAXkoEaZRB9OtFblQ19ZPUT5UjucX52-9NzWR3aBcMec9NK5PvnCdXdFxAJoGgK_BsGDswJW0BdEgwdASC2OveifZdcFvCQ_IMrmBucgU5MBchSE4NLe_s8dmw2Ge2llM/file?dl=1# [following]
--2023-04-04 15:06:24--  https://uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com/cd/0/get/B5gpbbCTnzZCiZiieBea8pMWQGbJ23D63L7ejpA053ciEAlNmWDQHGedfiSn7kZEdplAXkoEaZRB9OtFblQ19ZPUT5UjucX52-9NzWR3aBcMec9NK5PvnCdXdFxAJoGgK_BsGDswJW0BdEgwdASC2OveifZdcFvCQ_IMrmBucgU5MBchSE4NLe_s8dmw2Ge2llM/file?dl=1
Resolving uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com (uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com)... 127.0.0.1
Connecting to uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com (uc9473414cea25b32ec2d6ecc563.dl.dropboxusercontent.com)|127.0.0.1|:443... failed: Connection refused.
```

Tried via browser as well. 

This  address: <https://www.dropbox.com/s/urciozkana5md0z/crisprme_test.tar.gz?dl=1>

```
This site can’t be reacheducbbeffe6fcc5ac3d70c313358f9.dl.dropboxusercontent.com refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED
```

Tried going up a directory and I can see the directory ```crisprme_test``` but when I try to download it produces an error. Same as when I go into the directory and try to download any of the files. A red error message at the top says "There was an error downloading your file."

**Comment by sdmiller93** [comment]
Ah, thank you Luca – yes it was the NIST network blocking it. I got it downloaded 😊


_______________________________________

Sierra D. Miller
Bioinformatician

Profile<https://www.nist.gov/people/sierra-miller> | NIST Genome Editing Program<https://www.nist.gov/programs-projects/nist-genome-editing-program>
Biomarker & Genomic Sciences Group<https://www.nist.gov/mml/bbd/bioassay-methods>
Biosystems and Biomaterials Division<https://www.nist.gov/mml/bbd>, MML<https://www.nist.gov/mml>
U.S. National Institute of Standards and Technology
[signature_2638166703]

Upcoming Out of Office Dates:

  *   April 14th
  *   Aug 29th – Sep 15th



From: Luca Pinello ***@***.***>
Date: Tuesday, April 4, 2023 at 3:36 PM
To: pinellolab/CRISPRme ***@***.***>
Cc: Miller, Sierra D. (Fed) ***@***.***>, Author ***@***.***>
Subject: Re: [pinellolab/CRISPRme] Is the dropbox test data not accessible anymore? (Issue #33)

Hi Sierra, could you please check if your network is blocking this request? I just tried and I can download the file. If you still have problems I can share this file in a different way. Thanks.

**Comment by lucapinello** [comment]
Glad this is solved! Please let us know if you have any other problems.
