### ISSUE TITLE
Test Installation Run Failure

### ISSUE THREAD

**Issue by sdmiller93** [pinellolab/CRISPRme#34]
**Describe the bug**

Terminal output: 
```
$ bash crisprme_auto_test_conda.sh
starting download and unzip of data
unzip gencode+encode annotations
start download VCF data and genome (this may take a long time due to connection speed)
download 1000G VCFs
crisprme_auto_test_conda.sh: line 26: 40706 Abort trap: 6           wget -c -q ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/ALL.chr$i.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
download hg38
start testing
Launching job /Users/sdm8/Desktop/crisprme_test/crisprme_test/Results/sg1617.6.2.2. The stdout is redirected in log_verbose.txt and stderr is redirected in log_error.txt
Traceback (most recent call last):
  File "/Users/sdm8/opt/anaconda3/envs/crisprme/bin/crisprme.py", line 934, in <module>
    complete_search()
  File "/Users/sdm8/opt/anaconda3/envs/crisprme/bin/crisprme.py", line 673, in complete_search
    raise OSError(f"\nCRISPRme run failed! See {os.path.join(outputfolder, 'log_error.txt')} for details\n")
OSError:
CRISPRme run failed! See /Users/sdm8/Desktop/crisprme_test/crisprme_test/Results/sg1617.6.2.2/log_error.txt for details
```

log_error.txt

```
[W::bcf_sr_add_reader] No BGZF EOF marker; file '/Users/sdm8/Desktop/crisprme_test/crisprme_test/VCFs/hg38_1000G/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz' may be truncated
mv: rename /Users/sdm8/Desktop/crisprme_test/crisprme_test/Genomes/variants_genome/SNPs_genome/hg38_enriched/ to ./hg38+hg38_1000G/: No such file or directory
```

**To Reproduce**

I had to install like this without specifying python version as described in README because I kept getting an error message pertaining to version one of the program:
 
```
Encountered problems while solving:
- package crisprme-1.0.1-0 requires crispritz, but none of the providers can be installed
```
 
Installed via:
```
mamba install -c bioconda crisprme
## missing module Bio -
mamba install biopython
```
 
I had to download test data off of my VPN (federal govt netowork), I downloaded the test data via:
```
wget https://www.dropbox.com/s/urciozkana5md0z/crisprme_test.tar.gz?dl=1 -O crisprme_test.tar.gz
tar -xvf crisprme_test.tar.gz
```

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**
- Python version 3.7.12
- CRISPRme version 2.1.1 
- CRISPRitz version 1.2.1 
- axel version 2.17.11
- gdown version 4.7.1 
- numpy version 1.20.0  
- dash version 1.10.0 
- dash-bootstrap-components version 0.10.0  
- dash-core-components version 1.9.0 
- dash-daq version 0.4.0 
- dash-html-components version 1.0.3 
- dash-renderer version 1.3.0  
- dash-table version 4.6.2
- flask version 1.1.3
- flask-caching version 1.7.1 
- flask-compress version 1.5.0   
- fontconfig version  2.13.1
- freetype version 2.10.1
- future version 0.18.2
- gettext version 0.19.8.1 
- gunicorn version 20.0.4  
- werkzeug version 1.0.1
- pandas version  1.2.5

**Comment by ManuelTgn** [comment]
Hi @sdmiller93,

it looks like the bash script to test CRISPRme failed while downloading 1000 Genomes VCF files. That explains the message in `log_error.txt`. Running again the script or downloading each VCF file individually should solve the issue.

To avoid the issue you encountered while installing CRISPRme via conda, you can specify the tool's version explicitly (sometimes it does not downloads the latest version automatically):
```
conda create -n crisprme python=3.8
conda activate crisprme
conda install crisprme=2.1.0
crisprme.py --help  # to test CRISPRme installation
```
Currently the latest version is v2.1.1, however we encountered some issues that we are trying to solve and we suggest to use v2.1.0. The differences between the two version only concern the handling of some error messages, while there are no major differences in the analysis.

Let us know if you have any further question!

Best,
Manuel
