### ISSUE TITLE
MemoryError in Enrichment step

### ISSUE THREAD

**Issue by joki-MG** [pinellolab/CRISPRme#36]
**Describe the bug**
When running the complete-search command there is a Memory Error in the Enrichment step. The folder titled `Genomes/hg38+hg38_1000G` that contains the reference enrichment fastas (ex: chr3.enriched.fa) is missing the two from the largest chromosomes: chr1.enriched.fa and chr2.enriched.fa. There is both chr1.fa and chr2.fa in the `Genomes/hg38` folder.

**To Reproduce**
Running final command in the crisprme_auto_test_conda.sh.

command:
`crisprme.py complete-search --genome Genomes/hg38/ --vcf list_vcf.txt/ --guide sg1617.txt --pam PAMs/20bp-NGG-SpCas9.txt --annotation Annotations/encode+gencode.hg38.bed --samplesID list_samplesID.txt --gene_annotation Annotations/gencode.protein_coding.bed --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output sg1617.6.2.2 --thread 4`

**Expected behavior**
Expect a list of off-target sites and some images. Instead some files are created but none including a full list of the off-target sites. No images are created in the img directory.

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**
- Python version: 3.8
- CRISPRme version: 2.1.1 
- CRISPRitz version: 2.6.6
- axel version: 2.17.11
- gdown version: 4.7.1 
- numpy version: 1.20.0   
- dash version: 1.10.0
- dash-bootstrap-components version: 0.10.0
- dash-core-components version: 1.9.0 
- dash-daq version: 0.4.0
- dash-html-components version: 1.0.3
- dash-renderer version: 1.3.0
- dash-table version: 4.6.2
- flask version: 1.1.3
- flask-caching version: 1.7.1
- flask-compress version: 1.5.0
- fontconfig version: 2.13.1 
- freetype version: 2.10.1 
- future version: 0.18.2
- gettext version: 0.19.8.1
- gunicorn version: 20.0.4  
- werkzeug version: 1.0.1
- pandas version: 1.2.5

**Additional context**
Running on a c4.4xlarge EC2 instance with 2Tb volume. 

[log_error_no_check.txt](https://github.com/pinellolab/CRISPRme/files/11512260/log_error_no_check.txt)

**Comment by lucapinello** [comment]
Hi Jennifer, if I am not wrong the this instance type has 30GB of RAM, can you try with an instance with at least 64GB of memory? @samuelecancellieri @ManuelTgn this should be enough right?

**Comment by joki-MG** [comment]
Hello @lucapinello, thank you so much for the suggestion. I will try that out. If there is a RAM requirement from CRISPRme, could you guys perhaps add this in the documentation? I think this would be helpful for future users.

**Comment by ManuelTgn** [comment]
Hi @joki-MG,

thank you so much for the suggestion! We added a line under **"Usage"** section in the `README`, specifying the minimum amount of memory required to run CRISPRme.

Best,
Manuel
