### ISSUE TITLE
CRISPRme ERROR: CFD radar chart report failed 

### ISSUE THREAD

**Issue by anurendra** [pinellolab/CRISPRme#39]
Gives me above error for few guides(not all). In particular L121 in radar_chart_dict_generator.py- 'if guide[count] == 'N':', error is IndexError: string index out of range.

**Comment by samuelecancellieri** [comment]
Hi @anurendra 
can you attach the full log_error and guide file with all the guides you are using?
I think the problem may be different lengths in the guides, since this is not expected.

Thanks a lot.

**Comment by samuelecancellieri** [comment]
hello @anurendra 

the problem i see in the guide you attached, is the absence of 'N's.
a guide should look like this,
AAAAAAAANNN
or
NNNNAAAAAAAAA
depending if the PAM sequence is upstream or downstream.

if you downloaded the test dataset, you have a file called sg1617.txt and this is how a guide should be written.
the software expected the presence of Ns in the guide sequence to identify the position of the PAM and the length.
add the Ns nucleotide in place of the PAM sequence attached to the guide, and this should solve the problem.

let me know.

thanks,
