### ISSUE TITLE
Seeking License information

### ISSUE THREAD

**Issue by hartzell** [pinellolab/CRISPRme#44]
I'm seeking information about acquiring a license to use CRISPRme at my company.

The [LICENSE doc](https://github.com/pinellolab/CRISPRme/blob/main/LICENSE) says:

> Please contact rosalba.giugno@univr.it and lpinello@mgh.harvard.edu for more information.

I've sent emails, but haven't heard back.  Is there newer or alternative contact information?

Thanks!

**Comment by samuelecancellieri** [comment]
No problem.

Ciao,

Il Sab 11 Nov 2023, 05:51 Luca Pinello ***@***.***> ha
scritto:
