### ISSUE TITLE
Error message: no results when using web based CRISPRme with Cas12a

### ISSUE THREAD

**Issue by LinHedehus1** [pinellolab/CRISPRme#45]
**Describe the bug**
Status report
Indexing genome(s): Not available
Searching spacer: Not available
Post processing: Not available
Merge targets: Not available
Annotating and generating images: Not available
Integrating results: Not available
Populating database: Not available

The selected result encountered some errors, please remove it and try to submit again

**To Reproduce**

If running CRISPRme via command line, type the command line call to CRISPRme returning the error

If running CRISPRme via the website, please fill the form below:
1. Spacer sequences
AGACAGATATTTGCATTGAGATA

2. Cas protein
Cas12a
3. PAM
TTTV-23bp-Cas12a
4. Genome
Hg38
5. Variants dataset (OPTIONAL)
plus 1000 Genomes Project variants
plus HGDP variants
6. Thresholds 
Mismatches: 6
DNA Bulges: 2
RNA Bulges: 2

7. Base editing (OPTIONAL)
Start: 7
Stop: 15
Nucleotide: A

8. Annotation

**Expected behavior**
I get an error and no results 

**Screenshots**
If running CRISPRme via website, add screenshots to help explain your problem.

<img width="2544" alt="Screenshot 2024-01-30 at 15 44 28" src="https://github.com/pinellolab/CRISPRme/assets/145494405/a0e5d721-1108-4cb0-aad2-ad93eedeaa80">
<img width="2551" alt="Screenshot 2024-01-30 at 15 44 45" src="https://github.com/pinellolab/CRISPRme/assets/145494405/dc9107d2-19e5-4b8f-9329-a1026c29c1cf">

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**
- Python version
- CRISPRme version
- CRISPRitz version
- axel version
- gdown version
- numpy version
- dash version
- dash-bootstrap-components version
- dash-core-components version
- dash-daq version
- dash-html-components version
- dash-renderer version
- dash-table version
- flask version
- flask-caching version
- flask-compress version
- fontconfig version
- freetype version
- future version
- gettext version
- gunicorn version
- werkzeug version
- pandas version

**Additional context**
I ran your test dataset with Cas9 and had no issues. I wonder if it has something to do with the Cas12a; I also tried different gRNAs for Cas12a with the same outcome

**Comment by ManuelTgn** [comment]
Hi @LinHedehus1,

unfortunately, our servers experienced an unexpected outage over the weekend, leading to a crash in the job queue on CRISPRme's website. We have since identified and resolved the issue, and the server is now fully operational. You are welcome to resubmit your query, and we apologize for any inconvenience caused.

Manuel
