### ISSUE TITLE
Update Dockerfile to pull v2.1.2

### ISSUE THREAD

**Issue by ManuelTgn** [pinellolab/CRISPRme#48]
Update and Fix Dockerfile:
- [x] Pull CRISPRme v2.1.2 instead of v2.1.1
- [x] Replace conda with mamba (use mamba miniforge image)
- [x] Force CRISPRitz = v2.6.6
- [ ] Update `crisprme_auto_test_docker.sh`
- [x] Test new build

**Comment by samuelecancellieri** [comment]
dockerfile updated.
next release will correct all the testing procedure.
