### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 48:cluster.dict.py

### ISSUE THREAD

**Issue by khl0798** [pinellolab/CRISPRme#52]
**I have faced the problems**
hg38+hg38_1000G_test_20bp-NGG-SpCas9.txt_guides.txt_gencode_encode.hg38.bed_6_2_2_chrX_KI270881v1_alt.total.cluster.txt.tmp_sort.txt file have specific symbols
<90> <E0> in third columns. And I had faced with error blows,I want to know if this problem can be solved,any ideas about how to solve this problem would be very grateful.
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/d327efbf-c5ac-4f89-b122-41624e8d0cfa)

**run command line**

crisprme.py complete-search --genome Genomes/hg38 --vcf list_vcf.txt/ --guide sg1617.txt --pam PAMs/20bp-NGG-SpCas9.txt --annotation Annotations/gencode_encode.hg38.bed --samplesID list_samplesID.txt --gene_annotation Gencode/gencode.protein_coding.bed --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output sg1617.6.2.2_new --thread 58

**8. Annotation**

I download the docker crispr using command line:
`docker pull pinellolab/crisprme
`
**file format** 
the third column have specific symbols,<90><E0>
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/8d527b06-8bdd-4361-ac67-9c1774b4e5e3)
Any help tracing this down would be helpful, I am looking forward to running the tool on a real sequence!

Let me know if any other information would be helpful...
khl

**Comment by ManuelTgn** [comment]
Hi @khl0798,

Could you kindly inform us of the version of CRISPRme you are currently using?

We've noticed similar issues in older versions of CRISPRme, leading us to suspect that the image you pulled may not be the latest version. We're investigating this matter.

In the meantime, you might consider building the image using the Dockerfile in the CRISPRme GitHub repository. Alternatively, you could use the image from Bioconda (https://bioconda.github.io/recipes/crisprme/README.html?highlight=crisprme#package-package%20'crisprme').

Please let us know if either of these options resolves the issue for you.

Best,
Manuel

**Comment by khl0798** [comment]
> Hi @khl0798,
> 
> Could you kindly inform us of the version of CRISPRme you are currently using?
> 
> We've noticed similar issues in older versions of CRISPRme, leading us to suspect that the image you pulled may not be the latest version. We're investigating this matter.
> 
> In the meantime, you might consider building the image using the Dockerfile in the CRISPRme GitHub repository. Alternatively, you could use the image from Bioconda (https://bioconda.github.io/recipes/crisprme/README.html?highlight=crisprme#package-package%20'crisprme').
> 
> Please let us know if either of these options resolves the issue for you.
> 
> Best, Manuel

Hi @Manuel,

Thank you for your prompt response. I'm planning to utilize the Docker image from Bioconda for CRISPRme, as recommended (https://bioconda.github.io/recipes/crisprme/README.html?highlight=crisprme#package-package%20'crisprme'), currently on version "v2.1.2".

Additionally, I've installed CRISPRme v2.1.2 via Conda. However, I've encountered an issue related to the Genome directory. It appears that several FASTA files are named in an unconventional format, such as "chr3_KI270934v1_alt.fa, chr8_KI270815v1_alt.fa, chrUn_KI270382v1.fa, chrUn_KI270591v1.fa".
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/eb015220-f09a-4f60-ba7a-eb7f10affc07)
This naming convention has led to the following error:
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/164f57a9-d690-4cd8-8247-7ffae1123bee)
Could you advise if it's safe to remove these files, namely "chr3_KI270934v1_alt.fa, chr8_KI270815v1_alt.fa, chrUn_KI270382v1.fa, chrUn_KI270591v1.fa"? I suspect these files might be the cause of the errors, and I'm considering retaining only the files shown below:
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/0c08f2ca-8261-4201-bb7b-36757c54eb6a)

Could you also provide some insight into the cause of the error? Additionally, I would appreciate guidance on how to execute the process smoothly without encountering any errors.

I'm looking forward to your guidance on this matter.

Thank you.
khl0798

**Comment by khl0798** [comment]
Hi @manuel,

Thank you for your prompt response. I want to extract some sampleID from vcf file. So
 I filter VCF file by selected sampleID, and got an error like this:
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/3363ad2f-00bc-4ba2-9dfe-8a6da04bcd9a)
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/6eea0c32-2562-4e3b-87c8-a1a79aaeeccb)
I want to know if I can filter samples by  VCF,and if I want to select sampleID from one country, 
![image](https://github.com/pinellolab/CRISPRme/assets/7838505/24c8a66c-c34b-4cd8-bbdd-5a04565fd577)

How should I proceed with the analysis?
Could you also provide some insight into the cause of the error? Additionally, I would appreciate guidance on how to execute the process smoothly without encountering any errors.

I'm looking forward to your guidance on this matter.

Thank you.
khl0798

**Comment by ManuelTgn** [comment]
Hi @khl0798,

Apologies for the delayed response.

As you suspected, the presence of non-canonical chromosomes is indeed causing the issue. CRISPRme does not consider variants linked to these chromosomes when constructing alternative genomic sequences from VCF files. Consequently, it fails to generate the variant-enriched FASTA files necessary for subsequent analysis steps. As a workaround, we recommend running CRISPRme exclusively on canonical chromosomes for now.

Regarding your second question,  CRISPRme typically requires data across populations to perform various post-processing analyses. However, you can still visualize the results specific to a certain population by using the GUI app. Simply launch the web interface by entering the following command in your terminal within the CRISPRme's directory tree:
```
crisprme.py web-interface
```
Once the local web interface is up and running, you can filter the data by population or even by individual sample in the "Summary by sample" tab.

Please let us know if these solutions resolve your issues.

Best,
Manuel
