### ISSUE TITLE
docker image version

### ISSUE THREAD

**Issue by mzhibo** [pinellolab/CRISPRme#62]
I pulled the newest docker image but somehow it says v.2.1.3
```
 docker images
REPOSITORY             TAG       IMAGE ID       CREATED         SIZE
pinellolab/crisprme    latest    a15be9acd5d6   38 hours ago    1.85GB
pinellolab/crispritz   latest    7d74a7bc0e48   3 months ago    3.22GB
hello-world            latest    d2c94e258dcb   15 months ago   13.3kB
zma@aws$ docker run -v ${PWD}:/DATA -w /DATA -i pinellolab/crisprme crisprme.py --version
v2.1.3
```
is there a chance the lastest docker image is actually an old one?

**Comment by ManuelTgn** [comment]
Hi @mzhibo,

Thank you for bringing this issue to our attention. We’ve updated the Dockerfile to install the latest version of CRISPRme (v2.1.5). The new Docker image, including CRISPRme v2.1.5, will be available on Docker Hub shortly.

Best regards,
Manuel
