### ISSUE TITLE
False indel-derived offtargets

### ISSUE THREAD

**Issue by thomas-davis** [pinellolab/CRISPRme#67]
**Describe the bug**

I suspect CRISRPme is occasionally reporting off-targets generated by indels that are False-- i.e. that are not actually generated by the reported indel

As part of an analysis, I generate oligos representing variant-containing off-target sequences with surrounding genomic context. 
To do this I'm extract the reference sequence and surrounding context for off-target sites reported in crisprme, and then introducing the reported SNP into the sequence. 95-99% of the time I am able to find the reported off-target in this extracted sequence. However rarely, for some indel associated off-targets, I am unable to find a sequence that matched the reported off-target. 

I can't send explicit examples unfortunately because they involve proprietary spacers, but I have observed this same bug across two versions of crisprme (v2.1.5 and v2.1.1). Is this a known bug? What other information would be helpful in tracking this down? I'm happy to disclose the code I'm using to add variants to the extracted sequence. If you have outputs for a public spacer I can take a look at whether the same bug is present and give concrete examples. The bug is preventing us from being able to use crisprme for our application. 

**To Reproduce**
Ran crisprme via the command line using HG38, 1000G + HGDP. 

```crisprme.py complete-search \
--genome Genomes/full_renamed \
--vcf 1000G_and_hgdp_list_vcf.txt \
--samplesID list_samplesID.txt \
--guide THE_NAME_OF_OUR_SPACER_spacer.txt \
--pam PAMs/20bp-FOO-CAS.txt \
--annotation Annotations/encode+gencode.hg38.bed \
--gene_annotation Annotations/encode+gencode.hg38.bed \
--mm 6 \
--bDNA 2 \
--bRNA 2 \
--bMax 2 \
--merge 3 \
--output THE_NAME_OF_OUR_SPACER \
--thread 64
```

1. Spacer sequences
I can't disclose this, apologies. Observed across two difference spacers. If need be I can try to reproduce with a public spacer. 
2. Cas protein
Also cannot disclose this. Effect observed across two different CAS's
3. PAM
Also cannot disclose this. Effect observed across two different PAMs

4. Genome
HG38
5. Variants dataset (OPTIONAL)
HGDP + 1000G
6. Thresholds 
Mismatches: 6 
DNA Bulges: 2 
RNA Bulges: 2 

**Expected behavior**
Indels should generate the expected off-target sequence

**Screenshots**
If running CRISPRme via website, add screenshots to help explain your problem.

**Environment (please complete the following information, ONLY applicable if running CRISPRme via command line):**
- Python version 3.9.15
- CRISPRme version 2.1.5 and 2.1.1
- CRISPRitz version 2.6.6
- axel version 2.17.11
- gdown version 5.2
- numpy version 1.20.0 
- dash version 1.10.0
- dash-bootstrap-components version 0.10
- dash-core-components version 1.9.0 
- dash-daq version 0.4.0
- dash-html-components version 1.0.3 
- dash-renderer version 1.3.0 
- dash-table version 4.6.2
- flask version 1.1.3
- flask-caching version 1.7.1
- flask-compress version 1.5.0
- fontconfig version 2.13.1
- freetype version 2.10.1
- future version 0.18.2
- gettext version 0.19.8.1
- gunicorn version 20.0.4
- werkzeug version 1.0.1
- pandas version 1.2.5

Thank you in advance for your help!

**Comment by ManuelTgn** [comment]
Hi @thomas-davis,

Thank you for bringing this issue to our attention. Could you kindly share the code you’re using to add variants to the sequences? This will help us replicate the behavior in CRISPRme using a public spacer, so we can investigate if the issue persists in a broader context.

Best,
Manuel

**Comment by ManuelTgn** [comment]
Hi @thomas-davis,

I am writing to follow up on the status of the scripts that were being adapted to utilize public guides for reproducing the unexpected behaviors observed in CRISPRme. We believe that having access to these scripts could be instrumental in helping us identify the underlying causes of the inconsistencies we have encountered.

Any updates or insights you could provide would be greatly appreciated, as they may help expedite our understanding and resolution of these issues.

Additionally, I would like to let you know that version 2.1.1 has been deprecated, as it contains a known bug that affects the correct reporting of targets generated by indels. We advise using a CRISPRme v2.1.5 or greater to avoid this issue, although you reported similar issues even running this tool's version. 

Thank you for your time and assistance.

Best,
Manuel

**Comment by thomas-davis** [comment]
Hey Manuel apologies I'll get back to you as soon as I can. 

We were also wondering what public spacer you'd planned to use for crisprme testing, ideally wanted to run it on our end as well to test our infrastructure. It is the one listed in sg1617.txt?

**Comment by lucapinello** [comment]
Yes, we can use that one for testing and reproducibility purposes.

Thanks!

Luca

**Comment by thomas-davis** [comment]
Sorry I still owe you code but side question-- we tried running sg1617 to replicate the bug and ran into error.

```
Traceback (most recent call last):
  File "/opt/conda/opt/crisprme/PostProcess/./new_simple_analysis.py", line 791, in <module>
    clusters_with_scores = calculate_scores(cluster_to_save)
  File "/opt/conda/opt/crisprme/PostProcess/./new_simple_analysis.py", line 566, in calculate_scores
    cluster_with_CRISTA_score = preprocess_CRISTA_score(cluster_to_save)
  File "/opt/conda/opt/crisprme/PostProcess/./new_simple_analysis.py", line 469, in preprocess_CRISTA_score
    crista_score_list_alt = CRISTA_predict_list(
  File "/opt/conda/opt/crisprme/PostProcess/CRISTA_score.py", line 399, in CRISTA_predict_list
    features = get_features(full_dna_seq=dna_seq_29nt, aligned_sgRNA=sgRNA_seq,
  File "/opt/conda/opt/crisprme/PostProcess/CRISTA_score.py", line 254, in get_features
    dna_enthalpy = sum([DNA_PAIRS_THERMODYNAMICS[gapless_dnaseq[i-1:i+1]]
  File "/opt/conda/opt/crisprme/PostProcess/CRISTA_score.py", line 254, in <listcomp>
    dna_enthalpy = sum([DNA_PAIRS_THERMODYNAMICS[gapless_dnaseq[i-1:i+1]]
KeyError: 'AR'
CRISPRme ERROR: annotation analysis failed (script: ./scriptAnalisiNNN_v3.sh line 97)
CRISPRme ERROR: SNP analysis failed (script: ./post_analisi_snp.sh line 33)
```

We were running the following with v2.1.5 of crisprme
Have you run 2.1.5 on the sg1617 spacer? Have you seen this crash before?
Thanks! 

```
crisprme.py complete-search \
--genome Genomes/full_renamed \
--vcf 1000G_and_hgdp_list_vcf.txt \
--samplesID list_samplesID.txt \
--guide sg1617_spacer.txt \
--pam PAMs/20bp-FOO-SpCas9.txt \
--annotation Annotations/encode+gencode.hg38.bed \
--gene_annotation Annotations/encode+gencode.hg38.bed \
--mm 5 \
--bDNA 2 \
--bRNA 2 \
--bMax 2 \
--merge 3 \
--output sg1617 \
--thread 64
cat Results/sg1617/log_error.txt
cat Results/sg1617/log_error_no_check.txt
```

**Comment by thomas-davis** [comment]
Also here's the notebook code. Currently run on a proprietary spacer, so I can't include intermediate outputs. 
[notebook_example.zip](https://github.com/user-attachments/files/17102999/notebook_example.zip)

**Comment by thomas-davis** [comment]
One last comment, one of my colleagues will be taking over this correspondence. Thanks in advance for your help.

**Comment by dkuo-ttx** [comment]
Hi, I'll be taking over correspondence for this issue from @thomas-davis. Let me know if there's anything else that's needed from our side and thanks!

**Comment by ManuelTgn** [comment]
Hi @thomas-davis and @dkuo-ttx,

Thank you for sharing the details. The error log is indeed unusual, and we haven’t encountered this issue before. We will thoroughly investigate the problem and work on identifying a solution.

Best,
Manuel

**Comment by ManuelTgn** [comment]
Hi @dkuo-ttx,

We attempted to reproduce the reported error using a different PAM, such as NAA, which seems similar to what you’re working with. However, we weren't able to replicate the issue, and the run completed smoothly. Below is the exact sequence of commands we executed for testing:
```
mamba create -n crisprme-2.1.5  # create fresh environment for CRISPRme v2.1.5
mamba activate crisprme-2.1.5  # activate the environment 
mamba install crisprme=2.1.5 -y  # install CRISPRme from bioconda targeting v2.1.5
crisprme.py --version  # v2.1.5
# run the tool -- 1000G + HGDP, NAA PAM
crisprme.py complete-search \
  --genome Genomes/hg38  \
  --vcf vcf_list_1000G_HGDP.txt \
  --samplesID samplesIDs_list_1000G_HGDP.txt \
  --guide sg1617_test_guide.txt \
  --pam PAMs/20bp-NAA-iSpyMacCas9.txt \
  --annotation Annotations/dhs+encode+gencode.hg38.bed \
  --gene_annotation Annotations/dhs+encode+gencode.hg38.bed \
  --mm 5 \
  --bDNA 2 \
  --bRNA 2 \
  --bMax 2 \
  --merge 3 \
  --output sg1617 \
  --thread 64

``` 

I've also attached the full log files for reference:
[log_error_no_check.txt](https://github.com/user-attachments/files/17201994/log_error_no_check.txt)
[log_verbose.txt](https://github.com/user-attachments/files/17201996/log_verbose.txt)
[log.txt](https://github.com/user-attachments/files/17201997/log.txt)

Could you please share the specific PAM sequence file you're using? There might be an issue related to that. Additionally, if the conversation may touch on any confidential information, we can switch to email to ensure everything remains secure.

Best,
Manuel

**Comment by dkuo-ttx** [comment]
Hi @ManuelTgn,

Thanks for the replies and apologies for my delay in getting back to you. My colleague was more deeply engaged in this issue so thanks also for your patience as I get up to speed.

Interesting that the run completed smoothly. We used this as the `sg1617` spacer: `CTAACAGTTGCTTTTATCAC` and had searched for an `NGG` pam when we ran into the issue. I'll try to run the code locally as you've described to see if it was maybe a deployment issue on our side.

I think once we can get the test spacer to run, we can assess the InDel bug together. I'll send another update in the next 2-3 days. Thank you!

**Comment by dkuo-ttx** [comment]
Hi @ManuelTgn , would it be possible for you to share this file with us for testing? `samplesIDs_list_1000G_HGDP.txt`

Thank you!

**Comment by ManuelTgn** [comment]
Hi @dkuo-ttx,

Before running the test, please ensure that both the [1000G sample IDs](https://raw.githubusercontent.com/pinellolab/CRISPRme/refs/heads/gnomad-4.1-converter/test/data/hg38_1000G.samplesID.txt) and [HGDP sample IDs](https://raw.githubusercontent.com/pinellolab/CRISPRme/refs/heads/gnomad-4.1-converter/test/data/hg38_HGDP.samplesID.txt) files are placed inside the samplesIDs folder. This folder is part of the directory structure required by CRISPRme (refer to the [directory structure guide](https://github.com/pinellolab/CRISPRme/tree/gnomad-4.1-converter#crisprme-directory-structure) for more details).

Once you've confirmed that the sample ID files are correctly stored in the samplesIDs folder, you can generate the configuration file samplesIDs_list_1000G_HGDP.txt by running the following commands in a terminal:
```
cd /path/to/crisprme/root/directory
printf "hg38_1000G.samplesID.txt\nhg38_HGDP.samplesID.txt\n" > samplesIDs_list_1000G_HGDP.txt
``` 

You can then pass this file to CRISPRme using the following parameter:
```
--samplesID samplesIDs_list_1000G_HGDP.txt
```

If you have any questions or need further clarification, feel free to reach out.

Best,
Manuel

**Comment by dkuo-ttx** [comment]
Hi @ManuelTgn ,

Some progress on our side as we are working through a vignette sample that ships with `CRISPRme`. We ran the `sg1617` spacer using the test vignette script provided as follows: 

* CRISPRme version 2.1.5 
* spacer `sc1617.txt` (`"CTAACAGTTGCTTTTATCACNNN"`) 

The command to run CRISPRme was: 
```
$ bash crisprme_auto_test_conda.sh
```

This produced this output file `CTAACAGTTGCTTTTATCACNNN+NGG_hg38+hg38_1000G_6+2_integrated_results.tsv` which we then parsed for potentially missing InDels.

Attached is a subset of InDels some of which are verified and others are problematic as designated in the `Indel_Verified` column. This output has 992 instances of problematic InDels (`Indel_Verified == FALSE`). [241022_sg1617_missingIndels.csv](https://github.com/user-attachments/files/17482912/241022_sg1617_missingIndels.csv)

```python
>>> import pandas as pd
>>> df = pd.read_csv('241022_sg1617_missingIndels.csv')
>>> df['Indel_Verified'].value_counts()

Indel_Verified
True     2326
False     992
```

All rows and columns here are a subset of the CRISPRme output except for the `Indel_Verified` column.

These problematic InDels do not appear in the genomic context after applying the CRISPRme reported variants from the column  `Variant_info_genome_(fewest_mm+b)` back to the reference genome.

We believe this is a bug in CRISPRme or we are not clear on how InDel variant information is factored into the detection of potential off-targets. Thanks for your help and please let us if you have any other questions. Cheers!

**Comment by ManuelTgn** [comment]
Hi @dkuo-ttx,

Thank you for sharing this report. We’re currently investigating potential causes of the observed issue with the indels and will update you as we make progress.

Best,
Manuel

**Comment by ManuelTgn** [comment]
Hi @thomas-davis and @dkuo-ttx,

We recently release a new version of CRISPRme (v2.1.6). This update specifically addresses and resolves the issue you raised regarding false indel-delivered off-target predictions.

We greatly appreciate your feedback, which was instrumental in identifying and resolving this issue. Please feel free to test the new version and let us know if you encounter any further issues or have suggestions for improvement.

Best,
Manuel
